- hosts: all
  gather_facts: no
  become: true
  pre_tasks:
    - name: 'Install Python for Ansible'
      raw: apt-get -y install python-simplejson
  tasks:
    - name: 'Install Apache'
      apt: name=apache2 state=present update_cache=yes